---
name: Prepare Zip File

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: Environment
        required: true
        default: "dev"
        options:
          - dev
          - staging
          - live
      release:
        type: string
        description: Release
        required: false
        default: ""

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      region: "eu-west-2"
      release: ${{ github.event.inputs.release }}

    steps:
      - name: checkout repo with release
        if: "${{ env.release != '' }}"
        uses: actions/checkout@v3
        with:
          ref: "${{ env.release }}"

      - name: checkout repo with branch
        if: "${{ env.release == '' }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure AWS Credentials for dev
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: eu-west-2
        when: github.event.inputs.deploy-environment == 'dev'

      - name: Configure AWS Credentials for staging
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_STAGING }}
          aws-region: eu-west-2
        when: github.event.inputs.deploy-environment == 'staging'

      - name: Configure AWS Credentials for live
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_LIVE }}
          aws-region: eu-west-2
        when: github.event.inputs.deploy-environment == 'live'

      - name: run prep script
        run: |
          cd ..
          zip -r tna-base-long-form.zip tna-base-long-form -x "*.git*"
          aws s3 cp tna-base-long-form.zip s3://ds-${{ github.event.inputs.deploy-environment }}-deployment-source/website/tna-base-long-form.zip
...
