---
name: Prepare Zip File

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: Environment
        required: true
        default: "dev"
        options:
          - dev
          - staging
          - live
      release:
        type: string
        description: Release
        required: false
        default: ""

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      region: "eu-west-2"
      release: ${{ github.event.inputs.release }}

    steps:
      - name: checkout repo with release
        if: "${{ env.release != '' }}"
        uses: actions/checkout@v3
        with:
          ref: "${{ env.release }}"

      - name: checkout repo with branch
        if: "${{ env.release == '' }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: run prep script
        run: |
          pwd
          cp tna-base-long-form/.github/files/appspec.yml ./appspec.yml
          cd ..
          zip -r tna-base-long-form.zip tna-base-long-form -x "*.git*"
          zip  tna-base-long-form/files/appspec.yml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: eu-west-2

      - name: Copy zip to S3
        run: |
          aws s3 cp tna-base-long-form.zip s3://ds-dev-deployment-source/website
...
